### ISSUE TITLE
Basic Http Auth

### ISSUE THREAD

**Issue by rodrigodiez** [salsita/go-jira#3]
I'd like to use IssueService with Http Basic Auth but access to the request object is needed in order to set the credentials

Am I missing any obvious way to configure the client or the service to achieve this?

BTW, thanks for your work, I am using this package in couple of personal projects with no issues appart of this

**Comment by tchap** [comment]
@rodrigodiez You can pass a `http.Client` to `NewClient`, so you can set the `Transport` field for that HTTP client to perform Basic auth:

``` go
type BasicAuthRoundTripper struct {
    Username string
    Password string
    Next     http.RoundTripper
}

func (rt *BasicAuthRoundTripper) RoundTrip(req *http.Request) (*http.Response, error) {
    req.SetBasicAuth(rt.Username, rt.Password)
    return rt.Next.RoundTrip(req)
}

func main() {
    // ...

    var httpClient http.Client
    httpClient.Transport = &BasicAuthRoundTripper{
        Username: "username",
        Password: "password",
        Next:     httpClient.Transport,
    }
    client := jira.NewClient(baseURL, &httpClient)

    // ...
}
```

BTW thanks, happy this package is useful for someone else as well :-)

**Comment by rodrigodiez** [comment]
Wow, thanks for the code samples! I did not know that the standard http Client could be configured in such way

I'll take this approach, thanks again for your hard work!

**Comment by tchap** [comment]
@rodrigodiez No problem. Actually there should be `return rt.Next.RoundTrip(req)` in the example. Fixed.
